### ISSUE TITLE
A few 404s in case you didn't notice

### ISSUE THREAD

**Issue by tegansnyder** [aidansteele/flowdog#1]
Excellent article btw https://awsteele.com/blog/2022/01/20/aws-gwlb-deep-packet-manipulatio.html
I noticed a few 404s. Example when I click:
<img width="762" alt="image" src="https://user-images.githubusercontent.com/1200195/159291881-9b91ffae-d139-4dc8-87bd-950526acf236.png">

**Comment by aidansteele** [comment]
Oh, thank you! I see I even had a typo in the page URL 😅 I've fixed those now
